# 配置文件入口
server:
  # 默认的健康服务监听地址
  port: 8081
  servlet:
    context-path: /app
spring:
  profiles:
    # 引用的其它配置，文件命名规则：application-${profile}.yml
    active: thrift,pulsar,redis,database,custom,replace
  main:
    web-application-type: SERVLET